export function generateReportHTML(data, sensors) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>ArogyaMitra Health Report</title>
  <style>
    body { font-family: Arial; margin: 40px; color:#111; }
    .header { text-align:center; border-bottom:2px solid #000; padding-bottom:10px; }
    .section { margin-top:20px; }
    table { width:100%; border-collapse:collapse; }
    td,th { border:1px solid #000; padding:8px; }
    .disclaimer { font-size:12px; color:#444; margin-top:20px; }
    .footer { margin-top:40px; font-size:12px; text-align:center; color:#555; }
  </style>
</head>

<body>
  <div class="header">
    <h1>ArogyaMitra – Smart Health Kiosk</h1>
    <p>Automated Preliminary Health Screening Report</p>
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>

  <div class="section">
    <h3>About ArogyaMitra</h3>
    <p>
      ArogyaMitra is an AI-powered remote health kiosk designed to provide
      quick, accessible and preliminary medical assessments in rural and
      underserved areas.
    </p>
  </div>

  <div class="section">
    <h3>Patient Information</h3>
    <table>
      <tr><td>Name</td><td>${data.name}</td></tr>
      <tr><td>Age</td><td>${data.age}</td></tr>
      <tr><td>Gender</td><td>${data.gender}</td></tr>
      <tr><td>Patient ID</td><td>${data.patientId || "--"}</td></tr>
      <tr><td>Location</td><td>${data.location || "--"}</td></tr>
    </table>
  </div>

  <div class="section">
    <h3>Vital Parameters</h3>
    <table>
      <tr><td>Heart Rate</td><td>${sensors.HeartRate?.value || "--"} BPM</td></tr>
      <tr><td>SpO2</td><td>${sensors.SpO2?.value || "--"} %</td></tr>
      <tr><td>Body Temperature</td><td>${sensors.TemperatureF?.value || "--"} °F</td></tr>
      <tr><td>Stress Level</td><td>${sensors.Stress?.value || "--"}</td></tr>
      <tr><td>Hydration</td><td>${sensors.Hydration?.value || "--"}</td></tr>
    </table>
  </div>

  <div class="section">
    <h3>Reported Symptoms</h3>
    <p>${data.symptoms || "No symptoms reported"}</p>
  </div>

  <div class="section">
    <h3>System Recommendation</h3>
    <p>
      Based on the recorded parameters, the patient is advised to
      consult a qualified medical professional for further diagnosis
      and treatment.
    </p>
  </div>

  <div class="disclaimer">
    <strong>Disclaimer:</strong>  
    This report is generated by an automated health screening system.
    It is not a medical diagnosis and should not be used as a substitute
    for professional medical advice.
  </div>

  <div class="disclaimer">
    <strong>Emergency Guidance:</strong>  
    In case of severe symptoms such as chest pain, difficulty breathing,
    unconsciousness, or abnormal vitals, immediately contact the nearest
    hospital or emergency services.
  </div>

  <p style="margin-top:40px">
    Doctor / Health Officer Signature: ___________________________
  </p>

  <div class="footer">
    Generated by ArogyaMitra Smart Health Kiosk  
    Empowering Remote Healthcare Through Technology
  </div>
</body>
</html>
`;
}
