export const authTranslations = {
  en: {
    auth_welcome: "Welcome to the medical kiosk authentication system",
    auth_signin_mobile_prompt: "Please enter your 10-digit mobile number to sign in",
    auth_signin_sendotp_tip: "Great! Now click the Send OTP button to receive your verification code",
    auth_otp_info: "We will send you a 6-digit verification code to your mobile number",
    auth_otp_input_label: "Please enter the 6-digit OTP you received on your mobile",
    auth_otp_verify_tip: "Enter all 6 digits and click verify to complete sign in",
    auth_signup_instruction: "You have switched to sign up mode. Please fill in your details to create a new account",
    auth_name_prompt: "Please enter your full name as it appears on your official documents",
    auth_mobile_prompt: "Now enter your 10-digit mobile number for verification",
    auth_dob_prompt: "Please select your date of birth using the dropdown menus",
    auth_dob_day: "First select the day you were born",
    auth_dob_month: "Now select the month of your birth",
    auth_dob_year: "Finally, select the year you were born",
    auth_gender_prompt: "Please select your gender from the available options",
    auth_aadhaar_prompt: "Now enter your 12-digit Aadhaar number for identity verification",
    auth_aadhaar_info: "Your Aadhaar information is secure and will be used only for verification purposes",
    auth_signup_continue_button: "Click the continue button to proceed with OTP verification",
  },
  hi: {
    auth_welcome: "मेडिकल कियोस्क प्रमाणीकरण प्रणाली में आपका स्वागत है",
    auth_signin_mobile_prompt: "साइन इन करने के लिए कृपया अपना दस अंकों का मोबाइल नंबर दर्ज करें",
    auth_signin_sendotp_tip: "बहुत बढ़िया! अब अपना सत्यापन कोड प्राप्त करने के लिए ओ टी पी भेजें बटन पर क्लिक करें",
    auth_otp_info: "हम आपके मोबाइल नंबर पर छह अंकों का सत्यापन कोड भेजेंगे",
    auth_otp_input_label: "कृपया अपने मोबाइल पर प्राप्त छह अंकों का ओ टी पी दर्ज करें",
    auth_otp_verify_tip: "सभी छह अंक दर्ज करें और साइन इन पूरा करने के लिए सत्यापित करें पर क्लिक करें",
    auth_signup_instruction: "आपने साइन अप मोड पर स्विच किया है। नया खाता बनाने के लिए कृपया अपना विवरण भरें",
    auth_name_prompt: "कृपया अपना पूरा नाम दर्ज करें जैसा कि आपके आधिकारिक दस्तावेजों में है",
    auth_mobile_prompt: "अब सत्यापन के लिए अपना दस अंकों का मोबाइल नंबर दर्ज करें",
    auth_dob_prompt: "कृपया ड्रॉप डाउन मेनू का उपयोग करके अपनी जन्म तिथि चुनें",
    auth_dob_day: "पहले अपने जन्म का दिन चुनें",
    auth_dob_month: "अब अपने जन्म का महीना चुनें",
    auth_dob_year: "अंत में, अपने जन्म का वर्ष चुनें",
    auth_gender_prompt: "कृपया उपलब्ध विकल्पों में से अपना लिंग चुनें",
    auth_aadhaar_prompt: "अब पहचान सत्यापन के लिए अपना बारह अंकों का आधार नंबर दर्ज करें",
    auth_aadhaar_info: "आपकी आधार जानकारी सुरक्षित है और केवल सत्यापन उद्देश्यों के लिए उपयोग की जाएगी",
    auth_signup_continue_button: "ओ टी पी सत्यापन के साथ आगे बढ़ने के लिए जारी रखें बटन पर क्लिक करें",
  },
}
